spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/nour
    username: postgres
    password: postgres
    hikari:
      schema: nour
  flyway:
    enabled: true
    baseline-version: 1
    baseline-on-migrate: true
    out-of-order: true
    url: jdbc:postgresql://localhost:5432/nour
    user: postgres
    password: postgres
    schemas: nour